# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-added-large-files
-   repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v13.0.0
    hooks:
    -   id: clang-format
        args:
        - "-style=file:developer-tools/.clang-format"
-   repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.8.0.3
    hooks:
    -   id: shellcheck
-   repo: https://github.com/jorisroovers/gitlint
    rev:  v0.17.0
    hooks:
    -   id: gitlint
        args:
        - "--config developer-tools/.gitlint"
